version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: muninn
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db